name: nes_ui
description: UI library inspired by old retro video game console
version: 0.18.0
repository: https://github.com/erickzanardo/nes_ui

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mini_sprite: ^0.0.1+1
  google_fonts: ">=4.0.3 <7.0.0"
  mini_sprite: ^0.1.0
  phased: ^0.0.3

dev_dependencies:
  alchemist:
    git:
      url: https://github.com/erickzanardo/alchemist
  flutter_test:
    sdk: flutter
  mocktail: ">=0.3.0 <2.0.0"
  very_good_analysis: ">=3.1.0 <6.0.0"

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/
