name: nes_ui
description: UI library inspired by old retro video game console
version: 0.3.0
repository: https://github.com/erickzanardo/flutter_nes

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mini_sprite: ^0.0.1
  google_fonts: ">=3.0.1 <5.0.0"
  mini_sprite: ^0.1.0
  phased: ^0.0.3

dev_dependencies:
  alchemist: ^0.6.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ">=3.1.0 <5.0.0"

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
