name: widgetbook_workspace
description: "Widgetbook workspace"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  nes_ui:
    path: ..
  widgetbook:
    git:
      url: https://github.com/widgetbook/widgetbook.git
      ref: v4
      path: packages/widgetbook

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
